### PR TITLE
Rewrite using Flask as web server

### PR DESCRIPTION
**Pull request by martinwheeler**
# Description

I was having a lot of issues running this project, namely the Seg Faults that others 
 https://github.com/meska/mjpeg_stream_webcam/issues/6 & https://github.com/meska/mjpeg_stream_webcam/issues/7 have mentioned. It would crash at random intervals and there was no easy way for me to reproduce the issue so I decided to rewrite the web server using Flask.

I have been running this stable for 3 hours so far without issue. I was seeing the crashes every 10-50 minutes with the current web server implementation.

The fix could be from the change to Flask or [the way I am a capturing the images](https://github.com/meska/mjpeg_stream_webcam/compare/master...martinwheeler:octoprint-video-feed:master#diff-6b632f92515dd40e8e8ddab0c09670762fb8e5a94f80a9729958880856ea678fR18) for the stream feed.

### CODE REVIEW

**Comment by martinwheeler** [comment]
Progress update: I have had this running over night for 10 hours and it is still running without fault.

**Comment by ynotgnap** [comment]
It work for me too thank you very much for the solution, have been finding the solution for a long time lol

**Comment by martinwheeler** [comment]
> It work for me too thank you very much for the solution, have been finding the solution for a long time lol, but python still sometime crash, may I know which version are you using ? just use start.sh will solve the crashing problem #6 ,tried on 3.7 and 3.10

I'm glad it's working for you. I'm using python 3.7 ATM.

I have a theory that opening the video stream from multiple places causes an issue and I think I have a way to solve that. I'll make an update in the next few days.

**Comment by gamersi** [comment]
Hello, sry for the delayed response, but I am the author of Issue #6 and got into this again today. I just saw this after tinkering around with the code myself and I have to thank you very much. it still crashes but way fewer and only if I really stress it and send a few requests per second.
I hope that @meska will merge this into the main branch because it works as long as you don't stress it.
thank you very much.
Greetings from Austria

**Comment by meska** [comment]
Good Work !

**Pull request merged**
